---
- name:
  hosts: ['node1','node3']
  become: true
  remote_user: ansible
  tasks:
  - name:
    service:
      name: httpd
      state: stopped
    when: ansible_hostname == 'node1' or ansible_hostname == 'node3'

